- lib/nimble_options.ex
- test/nimble_options_test.exs
Closes #14.
Implementation is kind of thrown out there, didn't spend too much time making things nice 😄 I'm also very interested in what format you think would work best. Not sure my choice of wording/error message is clear to read. Any ways, this is a first pass to get something working at least, because without this my experience has been that it's really hard to figure out where an error message is coming from. :)
cc @josevalim @msaraiva
> Support a context when showing error messages

- lib/nimble_options.ex
- lib/nimble_options/docs.ex
- test/nimble_options_test.exs
So as it turns out, `NimbleOptions.docs/1` wouldn't work with "normal" schemas. It only worked with the "special" schema used to validate the schemas themselves. That is, if I called
```elixir
NimbleOptions.docs([producer: [type: :atom]])
```
then it wouldn't generate any docs because `docs/1` only looks for `:keys`. I fixed this but now you can't provide a subsection (through `:doc`) to appear right after `## Options`. This is expected because if my schema is `[producer: [type: :atom]]`, there's nowhere to pass the "main" doc, only options-specific docs. So, I added an optional paramter to `docs/1`. Thoughts @josevalim and @msaraiva?
> Allow complete schema to be passed when generating docs

- lib/nimble_options.ex
- lib/nimble_options/docs.ex
- test/nimble_options_test.exs
Closes #23.
* We don't show an option in the docs if `doc: false`
* We don't show the entire subsection in the docs if the parent option has `doc: false`
> Add support for "doc: false"

- lib/nimble_options.ex
I just started checking this library, and it looks great, thanks for your hard
work.
I _think_ these two cases of the private function `reduce_options/2` are not
reachable, sorry in advance if that's not the case. I did review the unit
tests, and there I don't see any code that could be reaching these functions.
> Remove unreachable code on `NimbleOptions`

- test/nimble_options_test.exs
This PR add missing unit tests for `NimbleOptions.validate_doc/1`, which is
used internally to validate docs on schema definition.
> Add unit tests for schema's doc validation

- lib/nimble_options.ex
The first time that I read this code:
```elixir
def validate(options, schema) do
case validate_options_with_schema_and_path(schema, options_schema()) do
```
and this one:
```elixir
defp validate_options_with_schema(opts, fun, path) when is_function(fun) do
validate_options_with_schema(opts, fun.(), path)
```
it confused me a bit, on the first `validate_options_with_schema_and_path/2` I don't see the path as an argument, in the second block of code, I see that the path is needed but the function name is `validate_options_with_schema`. So, my best guess is that we should switch the function names and that's what I did here.
> Switch function names

- lib/nimble_options.ex
- test/nimble_options_test.exs
Hello! I was looking to use this library in a project of mine, but one of the types I'm passing is a PID. 
This PR adds `:pid` to possible types. I *think* I've updated all of the documentation and added the correct tests. Please let me know if I missed something!
Edit: I also wasn't sure if I should update the changelog, or if that only got updated when a release went out.
> Add pid type

- lib/nimble_options.ex
- lib/nimble_options/validation_error.ex
- test/nimble_options_test.exs
Closes #37.
This is a breaking change. Instead of returning `{:error, string}`, now we return `{:error, %NimbleOptions.ValidationError{}}` everywhere. For now this error has the message and the path to the failing option but we can change it however we want in the future.
cc @leandrocp @kevinkoltz
> Return structured errors everywhere

- CHANGELOG.md
- lib/nimble_options.ex
- lib/nimble_options/validation_error.ex
- test/nimble_options_test.exs
Provides programmatic access, to enable intelligent handling of errors (with one example being providing a fallback)
Fixes #46
> Return `:key` and `:value` for errors

- lib/nimble_options.ex
- test/nimble_options_test.exs
Currently, default values are not validated so if the user changes the schema and forgets to update related default values accordingly, the resulting options returned by `validate` will contain invalid options. This PR fixes the issue and also allows addressing #49 more consistently by setting `[]` as a default value.
> Validate default values

- lib/nimble_options.ex
- test/nimble_options_test.exs
It's missing docs still, but I think this is a pretty low hanging fruit. Reasons why I'm okay with this:
* the error message comes out nicely by combining all the error messages
* "casting" works okay by just casting as the first matching type
* I've used this a billion times through `{:custom, ...}` in my code already eheh
Thoughts before I write docs? :)
> Introduce a :or type

- lib/nimble_options.ex
- test/nimble_options_test.exs
@josevalim I completely overlooked nested schemas in #54. This to me seems like the best (= least horrible, still pretty ugly) way of dealing with them.
```elixir
schema = [
docs: [
type: {:or, [:boolean, {:keyword_list, enabled: [type: :boolean]}]}
]
]
```
Thoughts?
> Support nested schemas in the :or type

- lib/nimble_options.ex
- lib/nimble_options/docs.ex
- test/nimble_options_test.exs
The nesting level allows to nest all options in the generated Markdown by the given level. This allows to have, for example, a nested `nested_schema` schema and use `NimbleOptions.docs/2` inside the documentation for another option:
```elixir
main_schema = [
my_key: [
type: {:or, [:string, keyword_list: nested_schema]},
doc: """
Either a string or a keyword list with keys:
#{NimbleOptions.docs(nested_schema, _nest_level = 1)}
"""
]
]
```
The options for the nested schema in `:my_key` will be nested by one level, producing the correct Markdown.
> Support a nesting level in NimbleOptions.docs/2

- lib/nimble_options.ex
- test/nimble_options_test.exs
I was a bit surprised that float is not available as a basic type. So, here it is.
> Add float type

- lib/nimble_options.ex
- lib/nimble_options/docs.ex
- test/nimble_options_test.exs
See https://github.com/dashbitco/nimble_options/issues/69
This change makes possible to obtain a valid schema, and then validate options directly without validating the schema itself whenever options are to be validated.
I defined the struct directly in the NimbleOptions module, instead of creating a NimbleOptions.Schema module, because from there, I guess a couple options could be added to the struct, that would be passed into the validation, if someday `validate/2` becomes `validate/3` and support validation options.
(this is also why the flag is called `schema_valid?` and not just `valid?`)
Have a nice day :)
> use a struct to wrap a valid schema and skip schema validation

- lib/nimble_options.ex
- test/nimble_options_test.exs
Ranges implement Enumerable and support `in`, so you should be able to
use them with the `{:in, choices}` type.
For example, to check if a value is a byte:
```elixir
schema = [decimals: [type: {:in, 0..255}]]
```
This commit adds that support.
> add `Range` support for `{:in, choices}` type

- mix.exs
I'm a big fan of being able to check out the lovely changelog notes right from hexdocs, like [in ex_doc](https://hexdocs.pm/ex_doc/changelog.html#content) itself.
What do you think?
> include changelog in docs

- lib/nimble_options.ex
`NimbleOptions.docs/2` takes both keyword list and `NimbleOptions` struct as a schema, but the `t/0` type seems to be put in the wrong place by mistake.
> Fix NimbleOptions.docs/2 type spec

- lib/nimble_options.ex
- test/nimble_options_test.exs
See docs below. I think it's a pretty nice addition and a fairly common scenario. For example, Xandra [would use it for a custom `{module, options}` tuple](https://github.com/lexhide/xandra/pull/209/files#diff-b4759000fcc9c0a5bf4b63a2cf875a6a4d6ee7844133cee728d238bc1bc6bef8R224-R225).
> Add :tuple type

- lib/nimble_options.ex
- test/nimble_options_test.exs
I think once we support `:pid`, it makes sense to support `:reference` too. I have an actual use case too, for some internal option validation in Xandra :smile:
> Add the :reference option type

- lib/nimble_options/docs.ex
- test/nimble_options_test.exs
Hi, this adds options types to the documentation generated with `NimbleOptions.docs/2`.
> Add types to autogenerated schema docs

- lib/nimble_options/docs.ex
- test/nimble_options_test.exs
Lists were not correctly indented before,
which means that if you wanted to add
multiline content inside the docs, it would
not be formatted properly and the default
would also be out of place. For example:
doc: """
Options are:
* :foo
* :bar
""", default: :foo
Would either not indent or add the default
line wrongly:
Options are:
* :foo
* :bar The default value is :bar.
This PR fixes it so lists are naturally indented
and the `nest_level` hack is no longer necessary.
We also remove types printing in complex cases,
because it ends up verbose and/or showing duplicate information.
> Fix formatting of lists

- lib/nimble_options/docs.ex
- test/nimble_options_test.exs
If an option of type `tuple` was defined a FunctionClauseError was raised because `NimbleOptions.Docs.get_raw_type_str` did not pattern match.
> Support `tuple` type in typedoc generation

- lib/nimble_options/docs.ex
- test/nimble_options_test.exs
If an option has `type: :map`, generate a corresponding typespec `map()`.  If it has `type: {:map, k, v}`, then generate a typespec `%{optional(k) => v}`.
Fixes #95.
> Support `:map` types in `option_typespec/1`.

- CHANGELOG.md
Adds changelog entries for
- https://github.com/dashbitco/nimble_options/pull/99
- https://github.com/dashbitco/nimble_options/pull/102
The markdown for the changelog can be previewed at https://github.com/axelson/nimble_options/blob/add-changelog-for-0.5.2/CHANGELOG.md
> Add changelog entry for 0.5.2

- lib/nimble_options.ex
If we keep it opaque, then it's my understanding that we cannot build `NimbleOptions.new!(...)` at **compile-time**, because Dialyzer will complain about opaque types then. :weary:
> Make t:NimbleOptions.t/0 public

- lib/nimble_options/docs.ex
- test/nimble_options_test.exs
When attempting to add `@type option() :: unquote(NimbleOptions.option_typespec(@definition))` to our project I was met with the following error
```
** (CaseClauseError) no case clause matching: {:tuple, [:string, :string]}
(nimble_options 0.5.2) lib/nimble_options/docs.ex:180: NimbleOptions.Docs.type_to_spec/1
(nimble_options 0.5.2) lib/nimble_options/docs.ex:250: NimbleOptions.Docs.type_to_spec/1
(nimble_options 0.5.2) lib/nimble_options/docs.ex:173: anonymous fn/1 in NimbleOptions.Docs.schema_to_spec/1
```
I have added a test that failed and fixed the issue by extending type_to_spec/1 to accept the tuple spec
As always - thanks for all you do and let me know if there are any changes you would like to see to this work!
> Fix schema_to_spec by adding tuple to `type_to_spec`

- lib/nimble_options/docs.ex
- test/nimble_options/docs_test.exs
First commit adds test to demonstrate missing functionality, second commit is my best guess at an implementation.
output of failing test:
```
1) test NimbleOptions.docs/1 autogenerated type docs (NimbleOptions.DocsTest)
test/nimble_options/docs_test.exs:293
** (FunctionClauseError) no function clause matching in NimbleOptions.Docs.get_raw_type_str/1
The following arguments were given to NimbleOptions.Docs.get_raw_type_str/1:
{:map, []}
Attempted function clauses (showing 10 out of 27):
defp get_raw_type_str(nil)
defp get_raw_type_str({:custom, _mod, _fun, _args})
defp get_raw_type_str(:mfa)
defp get_raw_type_str(:mod_arg)
defp get_raw_type_str({:or, _values})
defp get_raw_type_str({:in, _})
defp get_raw_type_str({:fun, arity})
defp get_raw_type_str(:any)
defp get_raw_type_str(:reference) …
```
> List of maps bug

- lib/nimble_options/docs.ex
- test/nimble_options/docs_test.exs
Adds deprecated information to docs.
Example from [Finch docs](https://hexdocs.pm/finch/Finch.html#start_link/1-pool-configuration-options)
| Before         |  After         |
:---------------:|:---------------:
> Add deprecated to docs

- lib/nimble_options.ex
Adds a union for `keyword() | map()` where needed so dialyzer doesn't complain when using maps 😄
> Adjust specs for map support

- lib/nimble_options.ex
- test/nimble_options_test.exs
This PR aims to close #127.
* In order to get the original opts when composing the error message, I extended the second argument of `reduce_options/2`.
* There is also a trivial modification that unifies the function signatures of `validate_unknown_options/2` and `validate_options/2`.
> I am not very confident in the elegance of this code; comments are welcome, and I am happy to make revisions.
> Fix value of "received options" in error message

- lib/nimble_options.ex
- test/nimble_options_test.exs
If I have the following:
```elixir
NimbleOptions.validate(opts, NimbleOptions.new!(schema))
```
Everything works fine, but if I do:
```elixir
NimbleOptions.validate(opts, schema)
```
It doesn't work 😢
> Allow map options in validate/2 when schema is a list

- lib/nimble_options.ex
- lib/nimble_options/validation_error.ex
- test/nimble_options/validation_error_test.exs
- test/nimble_options_test.exs
Wanted to get some initial work in front of you all to make sure my approach is acceptable.
My main concern with this implementation is trying to centralize the redact logic as much as I can. Since this is a security minded feature I want to make sure that future contributors don't need to implement redaction themselves so I'm making it part of the implementation pattern for types.
Let me know if you feel like I'm on the right track or not. Open to suggestions as well.
> Support redacting sensitive options

- test/nimble_options_test.exs
Ran into a testing issue while working on #134 and saw `describe` being used instead of `test`.
> Fixed `describe` block that should be `test`

- lib/nimble_options.ex
Before, the doc uses `mod.fun(values, ...args)` to describe the usage of custom type. However, it failed to clearly explain the underlying approach, because `...` is not a valid syntax of Elixir.
This PR try to clarify the usage by referring the underlying call. 
> Although covering the underlying implementation in the documentation is not ideal, it is likely the easiest way to understand how things work, especially since developers are indeed required to implement certain aspects here.
> Clarify the usage of custom type

- lib/nimble_options.ex
- test/nimble_options_test.exs
Currently, schemas with wildcard-key defined misbehave:
```elixir
iex(1)> NimbleOptions.validate [], [table: [doc: "ETS table to use", type: :atom, default: nil], *: [type: :any]]
{:ok, []}
iex(2)> NimbleOptions.validate [], [table: [doc: "ETS table to use", type: :atom, default: nil]]
{:ok, [table: nil]}
```
The reason is that `NimbleOptions.expand_star_to_option_keys/2` ignores all other keys, except *present in the data* when handling wildcard.
Is that intended?
> Fix ignoring schema when wildcard-key is defined
